# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/triangulationbase.ui'
#
# Created: Fri Jun 24 13:21:12 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_TriangulationDialog(object):
    def setupUi(self, TriangulationDialog):
        TriangulationDialog.setObjectName(_fromUtf8("TriangulationDialog"))
        TriangulationDialog.setEnabled(True)
        TriangulationDialog.resize(569, 584)
        TriangulationDialog.setFocusPolicy(QtCore.Qt.NoFocus)
        TriangulationDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        TriangulationDialog.setSizeGripEnabled(True)
        self.gridLayout_5 = QtGui.QGridLayout(TriangulationDialog)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupBox_3 = QtGui.QGroupBox(TriangulationDialog)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.cmbFixIdField = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFixIdField.sizePolicy().hasHeightForWidth())
        self.cmbFixIdField.setSizePolicy(sizePolicy)
        self.cmbFixIdField.setObjectName(_fromUtf8("cmbFixIdField"))
        self.gridLayout_3.addWidget(self.cmbFixIdField, 3, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 3, 2, 1, 1)
        self.cmbXField = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbXField.sizePolicy().hasHeightForWidth())
        self.cmbXField.setSizePolicy(sizePolicy)
        self.cmbXField.setObjectName(_fromUtf8("cmbXField"))
        self.gridLayout_3.addWidget(self.cmbXField, 3, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 4, 0, 1, 1)
        self.cmbBearingField = QtGui.QComboBox(self.groupBox_3)
        self.cmbBearingField.setObjectName(_fromUtf8("cmbBearingField"))
        self.gridLayout_3.addWidget(self.cmbBearingField, 4, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 4, 2, 1, 1)
        self.cmbYField = QtGui.QComboBox(self.groupBox_3)
        self.cmbYField.setObjectName(_fromUtf8("cmbYField"))
        self.gridLayout_3.addWidget(self.cmbYField, 4, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.cmbInLayer = QtGui.QComboBox(self.groupBox_3)
        self.cmbInLayer.setObjectName(_fromUtf8("cmbInLayer"))
        self.gridLayout_3.addWidget(self.cmbInLayer, 0, 1, 1, 3)
        self.cmbDateTimeField = QtGui.QComboBox(self.groupBox_3)
        self.cmbDateTimeField.setObjectName(_fromUtf8("cmbDateTimeField"))
        self.gridLayout_3.addWidget(self.cmbDateTimeField, 5, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 5, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 0, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(TriangulationDialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.ckbAddPointsToCanvas = QtGui.QCheckBox(self.groupBox)
        self.ckbAddPointsToCanvas.setToolTip(_fromUtf8(""))
        self.ckbAddPointsToCanvas.setObjectName(_fromUtf8("ckbAddPointsToCanvas"))
        self.gridLayout.addWidget(self.ckbAddPointsToCanvas, 0, 0, 1, 1)
        self.linePointLayerName = QtGui.QLineEdit(self.groupBox)
        self.linePointLayerName.setEnabled(False)
        self.linePointLayerName.setObjectName(_fromUtf8("linePointLayerName"))
        self.gridLayout.addWidget(self.linePointLayerName, 0, 2, 1, 2)
        self.ckbSavePoints = QtGui.QCheckBox(self.groupBox)
        self.ckbSavePoints.setToolTip(_fromUtf8(""))
        self.ckbSavePoints.setObjectName(_fromUtf8("ckbSavePoints"))
        self.gridLayout.addWidget(self.ckbSavePoints, 1, 0, 1, 2)
        self.linePointFileName = QtGui.QLineEdit(self.groupBox)
        self.linePointFileName.setEnabled(False)
        self.linePointFileName.setObjectName(_fromUtf8("linePointFileName"))
        self.gridLayout.addWidget(self.linePointFileName, 1, 2, 1, 1)
        self.butPointFileName = QtGui.QToolButton(self.groupBox)
        self.butPointFileName.setEnabled(False)
        self.butPointFileName.setObjectName(_fromUtf8("butPointFileName"))
        self.gridLayout.addWidget(self.butPointFileName, 1, 3, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 6, 0, 1, 2)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.butAbout = QtGui.QPushButton(TriangulationDialog)
        self.butAbout.setObjectName(_fromUtf8("butAbout"))
        self.hboxlayout.addWidget(self.butAbout)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.progressBar = QtGui.QProgressBar(TriangulationDialog)
        self.progressBar.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty(_fromUtf8("value"), 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.hboxlayout.addWidget(self.progressBar)
        self.butRun = QtGui.QPushButton(TriangulationDialog)
        self.butRun.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butRun.sizePolicy().hasHeightForWidth())
        self.butRun.setSizePolicy(sizePolicy)
        self.butRun.setObjectName(_fromUtf8("butRun"))
        self.hboxlayout.addWidget(self.butRun)
        self.buttonBox = QtGui.QDialogButtonBox(TriangulationDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.hboxlayout.addWidget(self.buttonBox)
        self.gridLayout_5.addLayout(self.hboxlayout, 8, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(TriangulationDialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.ckbAddPolygonsToCanvas = QtGui.QCheckBox(self.groupBox_2)
        self.ckbAddPolygonsToCanvas.setToolTip(_fromUtf8(""))
        self.ckbAddPolygonsToCanvas.setObjectName(_fromUtf8("ckbAddPolygonsToCanvas"))
        self.gridLayout_2.addWidget(self.ckbAddPolygonsToCanvas, 0, 0, 1, 1)
        self.linePolygonLayerName = QtGui.QLineEdit(self.groupBox_2)
        self.linePolygonLayerName.setEnabled(False)
        self.linePolygonLayerName.setObjectName(_fromUtf8("linePolygonLayerName"))
        self.gridLayout_2.addWidget(self.linePolygonLayerName, 0, 2, 1, 2)
        self.ckbSavePolygons = QtGui.QCheckBox(self.groupBox_2)
        self.ckbSavePolygons.setToolTip(_fromUtf8(""))
        self.ckbSavePolygons.setObjectName(_fromUtf8("ckbSavePolygons"))
        self.gridLayout_2.addWidget(self.ckbSavePolygons, 1, 0, 1, 2)
        self.linePolygonFileName = QtGui.QLineEdit(self.groupBox_2)
        self.linePolygonFileName.setEnabled(False)
        self.linePolygonFileName.setObjectName(_fromUtf8("linePolygonFileName"))
        self.gridLayout_2.addWidget(self.linePolygonFileName, 1, 2, 1, 1)
        self.butPolygonFileName = QtGui.QToolButton(self.groupBox_2)
        self.butPolygonFileName.setEnabled(False)
        self.butPolygonFileName.setObjectName(_fromUtf8("butPolygonFileName"))
        self.gridLayout_2.addWidget(self.butPolygonFileName, 1, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 4)
        self.gridLayout_5.addWidget(self.groupBox_2, 7, 0, 1, 2)
        self.groupBox_4 = QtGui.QGroupBox(TriangulationDialog)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem2 = QtGui.QSpacerItem(61, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 3, 0, 1, 2)
        self.ckbDiscardTooBigAreas = QtGui.QCheckBox(self.groupBox_4)
        self.ckbDiscardTooBigAreas.setObjectName(_fromUtf8("ckbDiscardTooBigAreas"))
        self.gridLayout_4.addWidget(self.ckbDiscardTooBigAreas, 1, 0, 1, 1)
        self.sbAreaThreshold = QtGui.QSpinBox(self.groupBox_4)
        self.sbAreaThreshold.setEnabled(False)
        self.sbAreaThreshold.setMinimum(1)
        self.sbAreaThreshold.setMaximum(999999)
        self.sbAreaThreshold.setObjectName(_fromUtf8("sbAreaThreshold"))
        self.gridLayout_4.addWidget(self.sbAreaThreshold, 1, 1, 1, 1)
        self.ckbDiscardDivergent = QtGui.QCheckBox(self.groupBox_4)
        self.ckbDiscardDivergent.setObjectName(_fromUtf8("ckbDiscardDivergent"))
        self.gridLayout_4.addWidget(self.ckbDiscardDivergent, 0, 0, 1, 2)
        self.gridLayout_5.addWidget(self.groupBox_4, 1, 0, 1, 2)
        self.ckbShowSummary = QtGui.QCheckBox(TriangulationDialog)
        self.ckbShowSummary.setObjectName(_fromUtf8("ckbShowSummary"))
        self.gridLayout_5.addWidget(self.ckbShowSummary, 2, 0, 1, 1)
        self.ckbShowLines = QtGui.QCheckBox(TriangulationDialog)
        self.ckbShowLines.setObjectName(_fromUtf8("ckbShowLines"))
        self.gridLayout_5.addWidget(self.ckbShowLines, 3, 0, 1, 1)
        self.label.setBuddy(self.cmbXField)
        self.label_8.setBuddy(self.cmbBearingField)
        self.label_9.setBuddy(self.cmbYField)
        self.label_7.setBuddy(self.cmbFixIdField)
        self.label_6.setBuddy(self.cmbInLayer)
        self.label_2.setBuddy(self.cmbDateTimeField)

        self.retranslateUi(TriangulationDialog)
        QtCore.QObject.connect(self.butRun, QtCore.SIGNAL(_fromUtf8("released()")), TriangulationDialog.accept)
        QtCore.QObject.connect(self.ckbDiscardTooBigAreas, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.sbAreaThreshold.setEnabled)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), TriangulationDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(TriangulationDialog)
        TriangulationDialog.setTabOrder(self.cmbInLayer, self.cmbFixIdField)
        TriangulationDialog.setTabOrder(self.cmbFixIdField, self.cmbBearingField)
        TriangulationDialog.setTabOrder(self.cmbBearingField, self.cmbDateTimeField)
        TriangulationDialog.setTabOrder(self.cmbDateTimeField, self.cmbXField)
        TriangulationDialog.setTabOrder(self.cmbXField, self.cmbYField)
        TriangulationDialog.setTabOrder(self.cmbYField, self.ckbDiscardDivergent)
        TriangulationDialog.setTabOrder(self.ckbDiscardDivergent, self.ckbDiscardTooBigAreas)
        TriangulationDialog.setTabOrder(self.ckbDiscardTooBigAreas, self.sbAreaThreshold)
        TriangulationDialog.setTabOrder(self.sbAreaThreshold, self.ckbShowSummary)
        TriangulationDialog.setTabOrder(self.ckbShowSummary, self.ckbShowLines)
        TriangulationDialog.setTabOrder(self.ckbShowLines, self.ckbAddPointsToCanvas)
        TriangulationDialog.setTabOrder(self.ckbAddPointsToCanvas, self.linePointLayerName)
        TriangulationDialog.setTabOrder(self.linePointLayerName, self.ckbSavePoints)
        TriangulationDialog.setTabOrder(self.ckbSavePoints, self.linePointFileName)
        TriangulationDialog.setTabOrder(self.linePointFileName, self.butPointFileName)
        TriangulationDialog.setTabOrder(self.butPointFileName, self.ckbAddPolygonsToCanvas)
        TriangulationDialog.setTabOrder(self.ckbAddPolygonsToCanvas, self.linePolygonLayerName)
        TriangulationDialog.setTabOrder(self.linePolygonLayerName, self.ckbSavePolygons)
        TriangulationDialog.setTabOrder(self.ckbSavePolygons, self.linePolygonFileName)
        TriangulationDialog.setTabOrder(self.linePolygonFileName, self.butPolygonFileName)
        TriangulationDialog.setTabOrder(self.butPolygonFileName, self.butAbout)
        TriangulationDialog.setTabOrder(self.butAbout, self.butRun)

    def retranslateUi(self, TriangulationDialog):
        TriangulationDialog.setWindowTitle(QtGui.QApplication.translate("TriangulationDialog", "AniMove: Triangulation", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("TriangulationDialog", "Input data", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("TriangulationDialog", "X coor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("TriangulationDialog", "Bearing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("TriangulationDialog", "Y coor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("TriangulationDialog", "Fix ID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("TriangulationDialog", "Source layer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("TriangulationDialog", "Date && time", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setToolTip(QtGui.QApplication.translate("TriangulationDialog", "select the first checkbox only to add a memory layer to mapcanvas, \n"
"the second checkbox only to save the output to disk, \n"
"or both checkboxes to save to file and then load it to the canvas", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("TriangulationDialog", "Output points", None, QtGui.QApplication.UnicodeUTF8))
        self.ckbAddPointsToCanvas.setText(QtGui.QApplication.translate("TriangulationDialog", "add to mapcanvas", None, QtGui.QApplication.UnicodeUTF8))
        self.linePointLayerName.setText(QtGui.QApplication.translate("TriangulationDialog", "a default layer name", None, QtGui.QApplication.UnicodeUTF8))
        self.ckbSavePoints.setText(QtGui.QApplication.translate("TriangulationDialog", "save to file", None, QtGui.QApplication.UnicodeUTF8))
        self.linePointFileName.setText(QtGui.QApplication.translate("TriangulationDialog", "teddy_bear.gml", None, QtGui.QApplication.UnicodeUTF8))
        self.butPointFileName.setText(QtGui.QApplication.translate("TriangulationDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.butAbout.setText(QtGui.QApplication.translate("TriangulationDialog", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.butRun.setText(QtGui.QApplication.translate("TriangulationDialog", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setToolTip(QtGui.QApplication.translate("TriangulationDialog", "select the first checkbox only to add a memory layer to mapcanvas, \n"
"the second checkbox only to save the output to disk, \n"
"or both checkboxes to save to file and then load it to the canvas", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("TriangulationDialog", "Output polygons", None, QtGui.QApplication.UnicodeUTF8))
        self.ckbAddPolygonsToCanvas.setText(QtGui.QApplication.translate("TriangulationDialog", "add to mapcanvas", None, QtGui.QApplication.UnicodeUTF8))
        self.linePolygonLayerName.setText(QtGui.QApplication.translate("TriangulationDialog", "a default layer name", None, QtGui.QApplication.UnicodeUTF8))
        self.ckbSavePolygons.setText(QtGui.QApplication.translate("TriangulationDialog", "save to file", None, QtGui.QApplication.UnicodeUTF8))
        self.linePolygonFileName.setText(QtGui.QApplication.translate("TriangulationDialog", "teddy_bear_poly.gml", None, QtGui.QApplication.UnicodeUTF8))
        self.butPolygonFileName.setText(QtGui.QApplication.translate("TriangulationDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("TriangulationDialog", "Error corrections", None, QtGui.QApplication.UnicodeUTF8))
        self.ckbDiscardTooBigAreas.setText(QtGui.QApplication.translate("TriangulationDialog", "Discard subsets with area of generated polygon exceeding", None, QtGui.QApplication.UnicodeUTF8))
        self.sbAreaThreshold.setSuffix(QtGui.QApplication.translate("TriangulationDialog", " m²", None, QtGui.QApplication.UnicodeUTF8))
        self.ckbDiscardDivergent.setToolTip(QtGui.QApplication.translate("TriangulationDialog", " Check this option to discard whole subset if any of bearing pairs\n"
" is divergent. Otherwise, only that pair is discarded and the location\n"
" is computed using all remaining combinations.", None, QtGui.QApplication.UnicodeUTF8))
        self.ckbDiscardDivergent.setText(QtGui.QApplication.translate("TriangulationDialog", "Discard subsets with divergent bearings", None, QtGui.QApplication.UnicodeUTF8))
        self.ckbShowSummary.setText(QtGui.QApplication.translate("TriangulationDialog", "Show summary", None, QtGui.QApplication.UnicodeUTF8))
        self.ckbShowLines.setText(QtGui.QApplication.translate("TriangulationDialog", "Show bearing lines and intersection points", None, QtGui.QApplication.UnicodeUTF8))

